### PR TITLE
fix: url in docs

### PR DESCRIPTION
**Pull request by piedcipher**
Fixes: #319

### CODE REVIEW

**Comment by piedcipher** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
@piedcipher – pretty sure this is already fixed internally. Stay tuned for the sync

**Comment by piedcipher** [comment]
Cool, Got it @kevmoo :+1: 

Someone asked a question about this lib on r/flutterdev discord and I noticed it.

**Comment by kevmoo** [comment]
Yeah, this PR became a noop w/ the latest sync. Thanks!

**Pull request closed without merging**
