### PR TITLE
Support runtime interception setting text

### PR DESCRIPTION
**Pull request by hai046**
Support post-setting of copywriting, such as setting problems in the later period such as holidays; if you find that the copywriting setting is wrong, you can incrementally replace it later

支持后期设置文案，例如后期在节假日等设置问题；发现文案设置错误后可以在后期增量替换

for example:

```dart
 static void init() async {
   // get local storage first
   // then config from server
    HttpUtils.get(Api.kvConfig, parameters:{}, success: (t) {
      var result = t as Map<String, dynamic>;
      var data = json.decode(result["val"]);
      if (data != null) {
        Intl.setTextInterceptor((messageText, locale, name, args, meaning) {
          if (data.containsKey(name)) {
            return data[name]!;
          }
          return "";
        });
      
        //setLocalStorage(key, data);
      }
      Log.i('get language from server $language success');
    }, fail: (code, t) {
      Log.e('get language from server error $language err');
    });
  

  }

```

### CODE REVIEW

**Comment by alanknight-wk** [comment]
Text lookup is already indirected through the MessageLookup code, which is generated via intl_translation. It would be better to change the MessageLookup code, but you can also just generate it differently to support this. You can see the https://github.com/jamesblasco/intl_translation_format repo for an example of and a framework for generating different lookup mechanisms and supporting different data formats.

**Comment by hai046** [comment]
> 

First of all thanks for your feedback, but I looked at the source code and the implementation didn't quite meet our requirements

The usage scenarios are different. We are an app that needs to be configured with different languages in different countries. We have pre-adapted different languages, such as pt.arb, en.arb and many other language packs, but after we released it, we found that the copy was not In line with their usage habits, incremental modifications are required, but if the republishing and packaging process is very long, we will rush the server to pull and cover the local copy within a certain visit.

**Comment by hai046** [comment]
> Text lookup is already indirected through the MessageLookup code, which is generated via intl_translation. It would be better to change the MessageLookup code, but you can also just generate it differently to support this. You can see the https://github.com/jamesblasco/intl_translation_format repo for an example of and a framework for generating different lookup mechanisms and supporting different data formats.

The usage scenarios are different. We are an app that needs to be configured with different languages in different countries. We have pre-adapted different languages, such as pt.arb, en.arb and many other language packs, but after we released it, we found that the copy was not In line with their usage habits, incremental modifications are required, but if the republishing and packaging process is very long, we will rush the server to pull and cover the local copy within a certain visit.

**Comment by hai046** [comment]
> I understand that it doesn't do what you want right away. However, that is already an interception point at which messages are looked up. So it is simpler and more consistent to adapt that interception point rather than adding a new one. And the interception point provided by intl_translation is in generated code, rather than in the package itself. So you can change the way that the code is generated by yourself, without needing to make any changes directly to either of those packages.
> 
> The intl_translation_format package that I referred to is an example of something that makes large changes to the generated code without needing to modify either intl or intl_translation. For example, we changed the code so that we can generate plain JSON data files rather than the JSON embedded in Dart code that it currently creates with the `--json` argument. Adding the ability to replace particular messages would be simpler.

Thanks again for your reply. I went to sort out the whole just now, and found that the overall discussion we discussed was biased. I am very sorry for the disturbance to you.
1. We are using the ide FlutterJsonBeanFactory plug-in, so some codes began to try to modify intl_utils , but found that his running environment is not easy to control
2. After running the modified templates.dart, it is found that the development process has been added, and some situations are uncontrollable
3. Because we have only one language for one package name, we only need to control the interception interface globally, and do not need to pre-judgment locale

Later, I tried the following 2 directions to achieve:
1. Use the company's private git to implement intl references to avoid the intrusive impact of our single scene on the project
2. I will try to modify intl_utils later to intercept the generated code.

**Comment by mosuem** [comment]
I assume this is resolved, closing for now.

**Pull request closed without merging**
