### PR TITLE
Add es_PE currency symbols

### PR DESCRIPTION
**Pull request by Rodrigolmti**
Hello, I'm developing a app that runs on Peru, and right now the numberFormatSymbols, and compactNumberSymbols does not support es_PE currency formatting. In my searches I think this is the properly currency formatting for Peru.

Thank you.

### CODE REVIEW

**Comment by eaqtronto** [comment]
Hi, these fix can be added to Intl dart plugin, because in Peru correct currency pattern is  S/ #,##0.00   but  in dart code currently is bad formatted: #,##0.00 S/.

So the symbol must be previos number, not after.

Problem reported since 2004 link: https://github.com/gwtproject/gwt/issues/8074

Any people can be help to fix this bug.
Thanks

**Comment by kevmoo** [comment]
CC @devoncarew

**Comment by Rodrigolmti** [comment]
This problems happen for any country of Latin America that use es_419, it needs to be added to all countries not only Peru.

**Comment by mosuem** [comment]
I am happy to include `es_PE` as a locale, see issue #517. The code will then be auto-generated from CLDR data with the next update.

**Pull request closed without merging**
