### PR TITLE
Added GN build file.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by zanderso** [comment]
This lgtm, but IIRC the intl package source of truth is somewhere else, and @alan-knight might need to land this change for us there.

**Comment by pylaligand** [comment]
Is this package different from say `func` in that respect?

**Comment by alan-knight** [comment]
I don't particularly know about func, but yes, it looks different. Note that all commits say "Created by MOE"

**Comment by pylaligand** [comment]
Found another way.

**Pull request closed without merging**
