### PR TITLE
GitHub Sync

### PR DESCRIPTION
**Pull request by davidmorgan**
This is an automatically generated pull request.

### CODE REVIEW

**Review by athomas — APPROVED** [review]
LGTM

**Comment by natebosch** [comment]
Copybara sync masked names to `a-googler` which has not signed the CLA but is OK to submit.

**Review by natebosch — APPROVED** [review]

**Comment by natebosch** [comment]
I'm going to land this with a failing CI since it's caused by a chrome update changing locale specific strings and it isn't clear how to work around that.

**Comment by kevmoo** [comment]
@natebosch – FYI – this PR reverted changes to the version of the package. Seems...broken

**Pull request merged**
