### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by athomas**

### CODE REVIEW

**Comment by athomas** [comment]
@kevmoo Any suggestions how to proceed here? I'm not sure why the tests are failing, but it seems to be Chrome 88 that's causing trouble here. Travis had successful builds on Chrome 87. Unless I'm missing something, perhaps we can land this and figure out the Chrome 88 issues once we're on Actions?

**Comment by kevmoo** [comment]
I'm not sure who the main owner of intl is any more, either.

@davidmorgan ?

Interesting to see if this test is running and passing internally

**Comment by davidmorgan** [comment]
Chatted with Alex; my team owns intl in google3, and syncing from google3->external as needed.

google3 isn't on Chrome 88 yet, when it rolls we'll need to fix the test there.

**Comment by natebosch** [comment]
I'd like to get https://github.com/dart-lang/intl/pull/362 landed and published - we'll ignore the failing CI for that PR since we know we're publishing exactly what passed CI previously with the published prerelease version. That one will impact the sync but I don't think it will cause too much trouble. I'll land and internal CL with the same changes.


I do think that after we get the publish done there should not be any blockers to land this PR. These files are not involved in the sync process, and don't introduce new failures. We have the problem of fixing the tests on the latest chrome either way, but doesn't specifically need to be tied to this PR.

**Comment by athomas** [comment]
@natebosch I'm assuming that this is still on your plate. Let me know in case I misunderstood.

**Pull request closed without merging**
