### PR TITLE
Implements a parsing short year format (ex: d.m.yy)

### PR DESCRIPTION
**Pull request by vgordievskiy**
This fix from Wrike Team.

### CODE REVIEW

**Comment by alan-knight** [comment]
I can't do anything with this without the CLA.

**Comment by alan-knight** [comment]
Ping. This needs a CLA. Otherwise I can't do anything with it, and we might as well close.

**Comment by vgordievskiy** [comment]
Yes, I signed it. I added my second email addres.

**Comment by alan-knight** [comment]
Thanks!

**Comment by altherat** [comment]
@alan-knight Can this be reviewed and considered? This is a significant problem as dates with a short year format cannot be parsed still 3 years later... Issue #123 related

**Comment by andrewmcdnz** [comment]
> OK, FINALLY taking a look at this. My apologies for letting it fall on the floor. It seems like a useful thing to add, and ICU4J does seem to have similar behavior when using either the SHORT format or a pattern with 'yy'. Concerns I have.
> 
> * I'm not sure this works, unless using an explicit pattern with 'yy', which doesn't localize. None of the patterns in date_time_patterns.dart have a 'yy', anything with a year goes to a single 'y'.
> * For the same reason, it means that you really can't control this, if we interpret a single 'y' as short then there's no way to parse a date without using this behavior.
> * Do we have some validation that this is the appropriate algorithm? Is it actually standard somewhere? Should we have an ability for people to control the offset? The APIs in general are a bit of a mess for this. ICU has patterns, named pattern constants that adapt to the locale, and the integer constants SHORT/MEDIUM/LONG/FULL. JS Intl doesn't parse dates at all.

It's disappointing to see that this PR was rejected without an alternative fix being proposed.
 
Are you aware that the current behaviour of setting the century to 0 is inconsistent with the description in this library's own date_format.dart (line 200)? This description talks about 80/20 behaviour for setting the century in its absence and even illustrates it with an example for format MM/dd/yy, stating 'the string '01/11/12' would be interpreted as Jan 11, 2012'.

Despite their issues, abbreviated years are unfortunately common in the world. Our application parses invoices created by third parties which often include shortened dates and this is outside of our control. It would be great to see this resolved so that those of us affected by this issue can return to using the official intl package rather than our own modified versions.

**Pull request closed without merging**
