### PR TITLE
Depend on package:ffi release rather than git branch

### PR DESCRIPTION
**Pull request by dcharkes**
I purged branches and then this broke. I think this should be the right release.

### CODE REVIEW

**Comment by mit-mit** [comment]
I think we can also remove the fixnum override?

**Comment by mit-mit** [comment]
cc @jakemac53 @natebosch

**Comment by jakemac53** [comment]
I think this package is developed internally as well, the change might need to land there cc @davidmorgan

**Comment by jakemac53** [comment]
(and yes fixnum can be updated to use the published `1.0.0-nullsafety.0` version)

**Comment by athomas** [comment]
Yes, we should do this internally. It's a bit tricky right now to import PRs until https://github.com/dart-lang/intl/pull/360 lands externally. Because the copybara import workflow is broken right now.

**Comment by athomas** [comment]
Created cl/355405532 to do this internally first. Closing this PR.

**Pull request closed without merging**
