### PR TITLE
Copybara sync

### PR DESCRIPTION
**Pull request by jamesderlin**

### CODE REVIEW

**Comment by jamesderlin** [comment]
cc @natebosch

**Comment by natebosch** [comment]
This LGTM but I'll let @davidmorgan do the review since I don't know the specific plans for managing this repo.

**Comment by davidmorgan** [comment]
Thanks James!

I don't know the right way to make googlebot happy :/ ... when I rolled `intl_translation` I did it by changing the author email address to my address. Nate, any ideas please? @srawlins?

**Comment by jamesderlin** [comment]
I think you can just replace the `cla: no`  label with `cla: yes` to manually override googlebot.  That's what I do with flutter.widgets repository.

**Comment by davidmorgan** [comment]
Thanks! That seems to work.

Documenting per googlebot's request: these commits are all authored by googlers, we're copying google3->github.

**Pull request merged**
