### PR TITLE
Add some modernizing changes and checks

### PR DESCRIPTION
**Pull request by matanlurey**
Main changes:

* Run `dartfmt`
* Add our safe/standard set of lints that already enforced internally
* Add a way to run all of the tests to avoid regressions by contributors
* Fix some strong-mode inference warnings that probably just started showing recently

### CODE REVIEW

**Comment by alan-knight** [comment]
Please do this as a CL, not a pull request.

**Comment by matanlurey** [comment]
Is pkg/intl part of the SDK? Any reason we couldn't switch this to github?

**Comment by alan-knight** [comment]
It's not part of the SDK. No reason we couldn't switch - it used to be, and at Dan's request I switched it to be internal.

**Comment by matanlurey** [comment]
I'll shoot him an email, thanks! If not, I'll redo it with gclient.

**Pull request closed without merging**
